# Generated by Django 3.0.2 on 2020-07-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='영화제목')),
                ('year', models.PositiveIntegerField(verbose_name='개봉년도')),
                ('rating', models.FloatField(verbose_name='영화평점')),
                ('genre', models.CharField(max_length=128, verbose_name='영화장르')),
                ('summary', models.TextField(verbose_name='영화개요')),
            ],
            options={
                'verbose_name': '영화리스트',
                'verbose_name_plural': '영화리스트',
                'db_table': '영화리스트',
            },
        ),
    ]
